### ISSUE TITLE
Ping is undefined?

### ISSUE THREAD

**Issue by johncsuti** [ohlookitsderpy/hastebin-bot#20]
| Pong! The ping is undefinedms.
i get that when i attempt to ping the bot

**Comment by johncsuti** [comment]
here is the full error trace...
root@discord:~/hastebin/hastebin-bot# npm start

> hastebin-bot@0.3.4 start /root/hastebin/hastebin-bot
> node index.js

Loading message.js!
Loading ready.js!
Loading haste.js!
Loading help.js!
Loading ping.js!
Loading stats.js!
Connected to Discord!
/root/hastebin/hastebin-bot/node_modules/discord.js/src/structures/MessageEmbed.js:443
      .flat(2)
       ^

TypeError: fields.flat is not a function
    at Function.normalizeFields (/root/hastebin/hastebin-bot/node_modules/discord.js/src/structures/MessageEmbed.js:443:8)
    at MessageEmbed.addFields (/root/hastebin/hastebin-bot/node_modules/discord.js/src/structures/MessageEmbed.js:259:42)
    at MessageEmbed.addField (/root/hastebin/hastebin-bot/node_modules/discord.js/src/structures/MessageEmbed.js:250:17)
    at Object.exports.run (/root/hastebin/hastebin-bot/commands/help.js:6:6)
    at module.exports (/root/hastebin/hastebin-bot/events/message.js:7:11)
    at Client.emit (events.js:198:13)
    at MessageCreateAction.handle (/root/hastebin/hastebin-bot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/root/hastebin/hastebin-bot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/root/hastebin/hastebin-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/root/hastebin/hastebin-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)

**Comment by davidcralph** [comment]
What discord.js and Node.js version are you using?

**Comment by eartharoid** [comment]
You need Node.JS v12 or above.

**Comment by johncsuti** [comment]
ah im running nodejs version 10.19.0 and discord.js is 12.something

**Comment by johncsuti** [comment]
using nodejs 12.x now got this 
![Capture](https://user-images.githubusercontent.com/22971404/93544902-1dfa2a00-f92d-11ea-8a02-dcab3c3f70e2.PNG)

**Comment by johncsuti** [comment]
root@discord:~/hastebin/hastebin-bot# npm start

> hastebin-bot@0.3.4 start /root/hastebin/hastebin-bot
> node index.js

Loading message.js!
Loading ready.js!
Loading haste.js!
Loading help.js!
Loading ping.js!
Loading stats.js!
Connected to Discord!
(node:386) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://hastebin.com/documents reason: Unexpected token < in JSON at position 0
    at /root/hastebin/hastebin-bot/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.run (/root/hastebin/hastebin-bot/commands/haste.js:15:11)
(node:386) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:386) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by davidcralph** [comment]
Thank you for providing this information. I will take a look into the issue.

**Comment by davidcralph** [comment]
Should be fixed as of ef5ab89c89284c6af30ef6ae987964440b4ebefa (tested on Node.js 14)

<img src='https://u.derpyenterprises.org/4rh7'>

**Comment by johncsuti** [comment]
Still getting this after pulling the new changes.

root@discord:~/hastebin/hastebin-bot# npm start

> hastebin-bot@0.3.5 start /root/hastebin/hastebin-bot
> node index.js

Loading message.js!
Loading ready.js!
Loading haste.js!
Loading help.js!
Loading ping.js!
Loading stats.js!
Connected to Discord!
(node:4565) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://hastebin.com/documents reason: Unexpected token < in JSON at position 0
    at /root/hastebin/hastebin-bot/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.run (/root/hastebin/hastebin-bot/commands/haste.js:14:17)
(node:4565) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4565) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by davidcralph** [comment]
The ping and stats issues have been fixed.

As for the haste issue, please try on the Hastebin site to see if it works, try other text and try another haste server (haste.powercord.dev is an example)

**Comment by johncsuti** [comment]
i tried on hastebin.com and it works if i use my webbrowser and i will try using haste.powercord.dev

**Comment by johncsuti** [comment]
thanks for that different link it works. Also sorry for the late reply i went out of town for a bit. I also am still having an issue where stats gives me this text " | I am on undefined guilds with undefined users!"
